server:
  port: 8081
  servlet:
    session:
      timeout: 3h

spring:
  profiles:
    active: test
  application:
    name: Spring-test
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
#  servlet:
#    multipart:
#      max-file-size: 5MB
#      max-request-size: 5MB


mybatis:
  type-aliases-package: com.sian
  mapper-locations: classpath*:/**/mapper/*SQL.xml
  configuration:
    map-underscore-to-camel-case: true
  #mapper-locations: classpath:mapper/*SQL.xml

logging:
  level:
    net:
      chndol:
        study:
          mybatissample:
            mapper: TRACE
    #org:
    #  springframework:
    #    security: DEBUG

---
spring:
  profiles: test
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://db.siansoft.co.kr:3306/dainbine?characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: dainbine
    password: dain12#$
    #url: jdbc:log4jdbc:mysql://db-q3prd.pub-cdb.ntruss.com:3306/dainbine?characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    #username: dainbine_lmu
    #password: Lmu5037!
---
spring:
  profiles: aws
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: 
    username: 
    password:
---

#spring:
#  resources:
#    cache:
#      period: 31553600
#    chain:
#      strategy:
#        content:
#          enabled: true
#          paths: /**
